# Generated by Django 3.2.4 on 2021-10-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkhandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=250)),
                ('admin_access', models.BooleanField(default=True)),
                ('add_class', models.BooleanField(default=True)),
                ('add_time', models.BooleanField(default=True)),
                ('add_teacher', models.BooleanField(default=True)),
            ],
        ),
    ]
