# Generated by Django 3.2.4 on 2021-10-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkhandler', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='buttons',
            field=models.BooleanField(default=True),
        ),
    ]
