# Generated by Django 3.2.4 on 2021-10-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkhandler', '0003_settings_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='autosend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='autosend_time',
            field=models.CharField(default='22:00', max_length=10),
        ),
    ]
