# Generated by Django 3.2.4 on 2021-10-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkhandler', '0004_auto_20211013_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=250)),
                ('count', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('urls', models.ManyToManyField(related_name='Notify_Urls', to='vkhandler.NotifyUrls')),
            ],
        ),
    ]
