# Generated by Django 3.2.4 on 2021-10-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkhandler', '0005_notify_notifyurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='text',
            field=models.TextField(default=None, max_length=5000),
            preserve_default=False,
        ),
    ]
