# Generated by Django 3.2.4 on 2021-10-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkhandler', '0006_notify_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=250)),
            ],
        ),
    ]
