# Generated by Django 3.2.4 on 2021-10-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkhandler', '0007_notifygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifygroup',
            name='album_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
