# Generated by Django 3.2.4 on 2021-10-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkhandler', '0008_notifygroup_album_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='notify_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='urls',
            field=models.ManyToManyField(related_name='Notifies', to='vkhandler.NotifyUrls'),
        ),
    ]
