# Generated by Django 3.2.4 on 2021-11-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkhandler', '0009_auto_20211016_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('chat_id', models.CharField(max_length=250)),
                ('users', models.JSONField()),
            ],
        ),
    ]
